import { createPortal } from 'react-dom';
import { useCallback, useEffect, useId, useLayoutEffect, useMemo, useRef, useState } from 'react';

export interface AppSelectOption { value:string; label:string; description?:string; disabled?:boolean; keywords?:string; }
interface Props { value:string; onChange:(value:string)=>void; options:readonly AppSelectOption[]; label:string; placeholder?:string; searchable?:boolean; allowCustom?:boolean; disabled?:boolean; className?:string; popoverMinWidth?:number; }

export default function AppSelect({value,onChange,options,label,placeholder='请选择',searchable=false,allowCustom=false,disabled,className='',popoverMinWidth=240}:Props){
  const id=useId(); const rootRef=useRef<HTMLDivElement>(null); const popoverRef=useRef<HTMLDivElement>(null);
  const [open,setOpen]=useState(false); const [query,setQuery]=useState(''); const [active,setActive]=useState(0); const [position,setPosition]=useState({left:0,top:0,width:240,maxHeight:280,above:false});
  const selected=options.find(item=>item.value===value);
  const filtered=useMemo(()=>{const needle=query.trim().toLocaleLowerCase();return options.filter(item=>!needle||`${item.label} ${item.value} ${item.keywords||''}`.toLocaleLowerCase().includes(needle));},[options,query]);
  const customValue=query.trim(); const canAdd=Boolean(allowCustom&&customValue&&!options.some(item=>item.value.toLocaleLowerCase()===customValue.toLocaleLowerCase()||item.label.toLocaleLowerCase()===customValue.toLocaleLowerCase()));
  const total=filtered.length+(canAdd?1:0);
  const activeOptionId=open&&total>0?`${id}-option-${active}`:undefined;
  const reposition=useCallback(()=>{const rect=rootRef.current?.getBoundingClientRect();if(!rect)return;const below=window.innerHeight-rect.bottom-12;const above=rect.top-12;const useAbove=below<190&&above>below;const width=Math.min(window.innerWidth-16,Math.max(rect.width,popoverMinWidth));setPosition({left:Math.max(8,Math.min(rect.left,window.innerWidth-width-8)),top:useAbove?rect.top-6:rect.bottom+6,width,maxHeight:Math.max(120,Math.min(320,(useAbove?above:below)-8)),above:useAbove});},[popoverMinWidth]);
  useLayoutEffect(()=>{if(open)reposition();},[open,reposition]);
  useEffect(()=>{if(!open)return;const outside=(event:PointerEvent)=>{const target=event.target as Node;if(!rootRef.current?.contains(target)&&!popoverRef.current?.contains(target)){setQuery('');setOpen(false);}};window.addEventListener('pointerdown',outside,true);window.addEventListener('resize',reposition);window.addEventListener('scroll',reposition,true);return()=>{window.removeEventListener('pointerdown',outside,true);window.removeEventListener('resize',reposition);window.removeEventListener('scroll',reposition,true);};},[open,reposition]);
  useEffect(()=>{if(!open)return;popoverRef.current?.querySelector<HTMLElement>(`[data-option-index="${active}"]`)?.scrollIntoView({block:'nearest'});},[active,open]);
  const choose=(next:string)=>{onChange(next);setQuery('');setOpen(false);requestAnimationFrame(()=>rootRef.current?.querySelector<HTMLElement>('[role="combobox"]')?.focus());};
  const openList=()=>{if(disabled)return;setOpen(true);setActive(Math.max(0,filtered.findIndex(item=>item.value===value)));};
  const onKeyDown=(event:React.KeyboardEvent)=>{if(event.key==='ArrowDown'){event.preventDefault();if(!open)openList();else setActive(i=>Math.min(Math.max(0,total-1),i+1));}else if(event.key==='ArrowUp'){event.preventDefault();if(!open)openList();else setActive(i=>Math.max(0,i-1));}else if(event.key==='Home'&&open){event.preventDefault();setActive(0);}else if(event.key==='End'&&open){event.preventDefault();setActive(Math.max(0,total-1));}else if(event.key==='Enter'&&open){event.preventDefault();const item=filtered[active];if(item&&!item.disabled)choose(item.value);else if(canAdd&&active===filtered.length)choose(customValue);}else if(event.key==='Escape'&&open){event.preventDefault();event.stopPropagation();setQuery('');setOpen(false);requestAnimationFrame(()=>rootRef.current?.querySelector<HTMLElement>('[role="combobox"]')?.focus());}else if(event.key==='Tab'&&open){setQuery('');setOpen(false);}};
  const portalTheme=document.documentElement.dataset.theme==='light'?'theme-light':'theme-dark';
  const popover=open&&createPortal(<div ref={popoverRef} id={id} className={`app-select-popover ${portalTheme} ${position.above?'above':''}`} role="listbox" aria-label={`${label}选项`} style={{left:position.left,top:position.top,width:position.width,maxHeight:position.maxHeight,transform:position.above?'translateY(-100%)':undefined}} onMouseDown={event=>event.preventDefault()}>
    <div className="app-select-options">{filtered.map((item,index)=><button id={`${id}-option-${index}`} type="button" role="option" data-option-index={index} aria-selected={item.value===value} className={`${index===active?'active':''} ${item.value===value?'selected':''}`} disabled={item.disabled} key={item.value} onMouseEnter={()=>setActive(index)} onClick={()=>choose(item.value)}><span><strong>{item.label}</strong>{item.description&&<small>{item.description}</small>}</span>{item.value===value&&<i aria-hidden="true">✓</i>}</button>)}
    {canAdd&&<button id={`${id}-option-${filtered.length}`} type="button" role="option" data-option-index={filtered.length} aria-selected={false} className={active===filtered.length?'active':''} onMouseEnter={()=>setActive(filtered.length)} onClick={()=>choose(customValue)}><span><strong>添加并选择“{customValue}”</strong><small>自定义项目</small></span></button>}{!filtered.length&&!canAdd&&<p>没有匹配项</p>}</div>
  </div>,document.body);
  return <div ref={rootRef} className={`app-select ${className}`}>
    {searchable?<input role="combobox" aria-label={label} aria-expanded={open} aria-controls={id} aria-activedescendant={activeOptionId} aria-autocomplete="list" value={open?query:(selected?.label||value)} placeholder={placeholder} disabled={disabled} onClick={openList} onChange={event=>{setQuery(event.target.value);if(!open)openList();setActive(0);}} onKeyDown={onKeyDown}/>:<button type="button" role="combobox" aria-label={label} aria-expanded={open} aria-controls={id} aria-activedescendant={activeOptionId} className="app-select-trigger" disabled={disabled} onClick={()=>open?setOpen(false):openList()} onKeyDown={onKeyDown}><span>{selected?.label||value||placeholder}</span><i aria-hidden="true">⌄</i></button>}
    {popover}
  </div>;
}
