import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import * as api from '../api/backend';

export default function GlossaryPanel({ projectId }: {projectId: string}) {
  const client = useQueryClient(); const [selected, setSelected] = useState('');
  const [source, setSource] = useState(''); const [target, setTarget] = useState(''); const [keep, setKeep] = useState(false);
  const [caseSensitive, setCaseSensitive] = useState(false); const [wholeWord, setWholeWord] = useState(true); const [note, setNote] = useState('');
  const [importData, setImportData] = useState<{content: string; delimiter: ',' | '\t'; preview: api.GlossaryImportPreview} | null>(null);
  const [message, setMessage] = useState('');
  const glossaries = useQuery({ queryKey: ['glossaries', projectId], queryFn: () => api.getGlossaries(projectId) });
  useEffect(() => { if (!selected && glossaries.data?.glossaries[0]) setSelected(glossaries.data.glossaries[0].id); }, [glossaries.data, selected]);
  const terms = useQuery({ queryKey: ['glossary-terms', selected], queryFn: () => api.getGlossaryTerms(selected), enabled: !!selected });
  const create = useMutation({ mutationFn: (name: string) => api.createGlossary(projectId, name), onSuccess: async item => { setSelected(item.id); await client.invalidateQueries({ queryKey: ['glossaries', projectId] }); } });
  const add = useMutation({ mutationFn: () => api.addGlossaryTerm(selected, { source_text: source, target_text: keep ? source : target, case_sensitive: caseSensitive, whole_word: wholeWord, do_not_translate: keep, note }), onSuccess: async () => { setSource(''); setTarget(''); setNote(''); await client.invalidateQueries({ queryKey: ['glossary-terms', selected] }); } });
  async function previewImport(file: File) { const content = await file.text(); const delimiter = file.name.toLowerCase().endsWith('.tsv') ? '\t' : ','; const preview = await api.importGlossaryTerms(selected, content, delimiter, false); setImportData({ content, delimiter, preview }); }
  async function commitImport() { if (!importData) return; const result = await api.importGlossaryTerms(selected, importData.content, importData.delimiter, true); setMessage(`已导入 ${result.new_count} 条，跳过 ${result.conflicts.length} 个冲突`); setImportData(null); await client.invalidateQueries({ queryKey: ['glossary-terms', selected] }); await client.invalidateQueries({ queryKey: ['glossaries', projectId] }); }
  return <aside className="glossary-panel"><header><div><small>项目与全局</small><h2>术语表</h2></div><button onClick={() => { const name = window.prompt('术语表名称'); if (name?.trim()) create.mutate(name.trim()); }}>新建</button></header>{glossaries.data?.glossaries.length ? <><select value={selected} onChange={event => { setSelected(event.target.value); setImportData(null); }}>{glossaries.data.glossaries.map(item => <option value={item.id} key={item.id}>{item.project_id ? '项目' : '全局'} · {item.name} ({item.term_count})</option>)}</select><div className="glossary-toolbar"><label className="button">导入 CSV/TSV<input type="file" accept=".csv,.tsv,text/csv,text/tab-separated-values" hidden onChange={event => { const file = event.target.files?.[0]; if (file) void previewImport(file); event.target.value = ''; }}/></label><button onClick={() => void api.downloadGlossary(selected, 'csv')}>导出 CSV</button><button onClick={() => void api.downloadGlossary(selected, 'tsv')}>导出 TSV</button></div>{importData && <div className="glossary-import-preview"><strong>导入预览：新增 {importData.preview.new_count} 条</strong><span>{importData.preview.conflicts.length} 个冲突将保留现有术语</span>{importData.preview.conflicts.slice(0, 4).map((item, index) => <small key={index}>{item.incoming.source_text} → 已有“{item.existing.target_text}”</small>)}<div><button onClick={() => setImportData(null)}>取消</button><button className="button primary" onClick={() => void commitImport()}>确认导入</button></div></div>}<div className="glossary-add"><input value={source} onChange={event => setSource(event.target.value)} placeholder="源词"/><input value={target} disabled={keep} onChange={event => setTarget(event.target.value)} placeholder="目标词"/><input value={note} onChange={event => setNote(event.target.value)} placeholder="备注（可选）"/><label><input type="checkbox" checked={caseSensitive} onChange={event => setCaseSensitive(event.target.checked)}/> 区分大小写</label><label><input type="checkbox" checked={wholeWord} onChange={event => setWholeWord(event.target.checked)}/> 整词匹配</label><label><input type="checkbox" checked={keep} onChange={event => setKeep(event.target.checked)}/> 禁止翻译</label><button disabled={!source.trim() || (!keep && !target.trim()) || add.isPending} onClick={() => add.mutate()}>添加术语</button></div><div className="glossary-terms">{terms.data?.terms.map(term => <div key={term.id}><strong>{term.source_text}</strong><span>→</span><em>{term.do_not_translate ? '保持原文' : term.target_text}</em><button aria-label={`删除 ${term.source_text}`} onClick={() => void api.deleteGlossaryTerm(selected, term.id).then(() => client.invalidateQueries({ queryKey: ['glossary-terms', selected] }))}>×</button></div>)}</div>{message && <p role="status">{message}</p>}</> : <div className="quality-empty"><strong>尚未创建术语表</strong><span>术语会自动注入翻译并参与质检。</span></div>}</aside>;
}
